# Dependencies
markdown:     kramdown
highlighter:  pygments

# Permalinks
permalink:    /blog/:title

# Collections
collections:
  - photos


# Setup
title:        Hugo
tagline:      'blog'
description:  'My personal blog.'
url:    
commentsystem:  
disqus:   

author:
  name:   'Me'
  url:    http://example.com

paginate: 5

# Custom vars
icon:   /assets/images/icon.png
cover:  /assets/images/cover.jpg

social:
  # - icon: twitter
  #   url:  https://twitter.com/iancamporez
  #   desc: Follow me on twitter

  # - icon: github
  #   url:  https://github.com/camporez
  #   desc: Fork me on github

  # - icon: googleplus-alt
  #   url:  https://google.com/+IanCamporezBrunelli
  #   desc: Add me on google+

  # - icon: feed
  #   url:  http://camporez.com/atom.xml
  #   desc: Subscribe to my feed

menu:
  - title:  Home
    url:    /

  - title:  Photos
    url:    /photos/japan

  - title:  About
    url:    /about

copyright:
  author:     Me
  url:        http://example.com
  type_title: Some rights reserved
  type_url:   http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
